# Generated by Django 6.0.1 on 2026-02-02 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.PositiveIntegerField(help_text='duration in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
