# Generated by Django 6.0.1 on 2026-02-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('meal_type', models.CharField(choices=[('BRK', 'Breakfast'), ('LUN', 'Lunch'), ('DIN', 'Dinner')], max_length=3)),
                ('calories', models.PositiveIntegerField()),
                ('proteins', models.DecimalField(decimal_places=2, help_text='Protein in grams', max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Carbs in grams', max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, help_text='Fats in grams', max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
