# Generated by Django 6.0.1 on 2026-02-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='daily_goal',
            field=models.IntegerField(default=2000, help_text='Daily calories target'),
        ),
    ]
